#!/usr/bin/env bash

## Commit/push changes in all my lab notebooks

CWD=$pwd
cd "$HOME/fmacrae/megadaph.private/megadaph"
git add lab_notebook.txt
git commit -m "Daily lab notebook commit"
git push -u origin master

cd "$HOME/fmacrae/daphnia-mtdna-ma.private/daphnia-mtdna-ma"
git add lab_notebook.txt
git commit -m "Daily lab notebook commit"
git push -u origin master

cd "$HOME/fmacrae/daphnia-maint"
git add lab_notebook.txt
git commit -m "Daily lab notebook commit"
git push -u origin master

cd $CWD
