#!/usr/bin/env bash

# Mount the mp3 player if necessary
MOUNTPOINT="/mnt/clip"
mkdir "$MOUNTPOINT"
mount "/dev/sda1" "$MOUNTPOINT"

# Move the episodes
for f in "/home/data/podcasts/*"
do
    if [[ -d "$f" ]]; then
        if eval cp -v "${f}/*" "$MOUNTPOINT/PODCASTS/"; then
            rm "$f/*"
        fi
    else
        if eval cp -v "$f" "$MOUNTPOINT/PODCASTS/"; then
            rm "$f"
        fi
    fi
done

unmount "/dev/sda1"
