#!/usr/bin/env bash

# Mount the mp3 player if necessary
sudo mkdir -p "/mnt/clip"
sudo mount "/dev/sda1" "/mnt/clip"

# Move the episodes
for f in "/home/data/podcasts/*"
do
    if [[ -d "$f" ]]; then
        if eval cp -vr "${f}/*" "/mnt/clip/PODCASTS/"; then
            rm "$f/*"
        fi
    else
        if eval cp -v "$f" "/mnt/0123-4567/PODCASTS/"; then
            rm "$f"
        fi
    fi
done
