#!/usr/bin/env python
"""Synchronize a directory between the CRC and local computer

Usage:
    unify <path>
"""
import sys

from plumbum import local

from fmbiopy.fmsystem import bash

if __name__ == '__main__':
    if len(sys.argv) == 2:
        if sys.argv[1] in ['--help', '-h']:
            print(__doc__)
            sys.exit(0)

        local = local.path(sys.argv[1])
    else:
        local = local.cwd()

    if 'fmacrae' not in local.parts:
        raise ValueError('Unify should only be called inside the shared dir')

    remote = local.relative_to(local.path('/') / 'home' / 'data')
    remote_address = 'ssh://schaack@ford.ibest.uidaho.edu:22/' + str(remote)
    local['unison', '-auto', '-batch', '-copythreshold', '50000', '-copyprog',
        'dummy', '-maxthreads', '8', local, remote_address]()
