#!/usr/bin/env python
"""Push the contents of current directory to matched folder on CRC.

Usage:
  push
  push (--help | -h)

Options:
  -h --help         Show this screen
"""
from fmbiopy.fmparse import helpful_docopt
from fmpersonalscripts.lib.crclib import (
        check_valid_location,
        map_local_to_remote,
        )
from plumbum import (
        FG,
        local,
        )
from plumbum.cmd import rsync

def push(*args):
    """Main function

    Parameters
    ----------
    args
        If run from another python script, command line args should be passed
        here
    """
    if args:
        opt = helpful_docopt(__doc__, args)
    else:
        opt = helpful_docopt(__doc__)

    local_path = local.cwd

    check_valid_location(local_path)

    remote = map_local_to_remote(local_path)
    rsync['--update', '-avz', local_path + '/', remote] & FG

if __name__ == '__main__':
    push()
